owner: ngshiheng
repo: train-service-alerts

delay: 5000 # seconds
sites:
    - name: Bukit Panjang LRT (BPL)
      url: $API_ENDPOINT
      icon: https://raw.githubusercontent.com/ngshiheng/train-service-alerts/main/assets/bpl.svg
      headers:
          - "AccountKey: $API_KEY"
          - "Content-Type: application/json"
      __dangerous__body_down: '"Status":2,"AffectedSegments":[{"Line":"BPL"'
      expectedStatusCodes:
          - 200
          - 500 # Rate limited
    - name: Changi Extension (CGL)
      url: $API_ENDPOINT
      icon: https://raw.githubusercontent.com/ngshiheng/train-service-alerts/main/assets/cgl.svg
      headers:
          - "AccountKey: $API_KEY"
          - "Content-Type: application/json"
      __dangerous__body_down: '"Status":2,"AffectedSegments":[{"Line":"CGL"'
      expectedStatusCodes:
          - 200
          - 500 # Rate limited
    - name: Circle Line (CCL)
      url: $API_ENDPOINT
      icon: https://raw.githubusercontent.com/ngshiheng/train-service-alerts/main/assets/ccl.svg
      headers:
          - "AccountKey: $API_KEY"
          - "Content-Type: application/json"
      __dangerous__body_down: '"Status":2,"AffectedSegments":[{"Line":"CCL"'
      expectedStatusCodes:
          - 200
          - 500 # Rate limited
    - name: Circle Line Extension (CEL)
      url: $API_ENDPOINT
      icon: https://raw.githubusercontent.com/ngshiheng/train-service-alerts/main/assets/cel.svg
      headers:
          - "AccountKey: $API_KEY"
          - "Content-Type: application/json"
      __dangerous__body_down: '"Status":2,"AffectedSegments":[{"Line":"CEL"'
      expectedStatusCodes:
          - 200
          - 500 # Rate limited
    - name: Downtown Line (DTL)
      url: $API_ENDPOINT
      icon: https://raw.githubusercontent.com/ngshiheng/train-service-alerts/main/assets/dtl.svg
      headers:
          - "AccountKey: $API_KEY"
          - "Content-Type: application/json"
      __dangerous__body_down: '"Status":2,"AffectedSegments":[{"Line":"DTL"'
      expectedStatusCodes:
          - 200
          - 500 # Rate limited
    - name: East-West Line (EWL)
      url: $API_ENDPOINT
      icon: https://raw.githubusercontent.com/ngshiheng/train-service-alerts/main/assets/ewl.svg
      headers:
          - "AccountKey: $API_KEY"
          - "Content-Type: application/json"
      __dangerous__body_down: '"Status":2,"AffectedSegments":[{"Line":"EWL"'
      expectedStatusCodes:
          - 200
          - 500 # Rate limited
    - name: North East Line (NEL)
      url: $API_ENDPOINT
      icon: https://raw.githubusercontent.com/ngshiheng/train-service-alerts/main/assets/nel.svg
      headers:
          - "AccountKey: $API_KEY"
          - "Content-Type: application/json"
      __dangerous__body_down: '"Status":2,"AffectedSegments":[{"Line":"NEL"'
      expectedStatusCodes:
          - 200
          - 500 # Rate limited
    - name: North-South Line (NSL)
      url: $API_ENDPOINT
      icon: https://raw.githubusercontent.com/ngshiheng/train-service-alerts/main/assets/nsl.svg
      headers:
          - "AccountKey: $API_KEY"
          - "Content-Type: application/json"
      __dangerous__body_down: '"Status":2,"AffectedSegments":[{"Line":"NSL"'
      expectedStatusCodes:
          - 200
          - 500 # Rate limited
    - name: Punggol LRT East Loop (PEL)
      url: $API_ENDPOINT
      icon: https://raw.githubusercontent.com/ngshiheng/train-service-alerts/main/assets/pel.svg
      headers:
          - "AccountKey: $API_KEY"
          - "Content-Type: application/json"
      __dangerous__body_down: '"Status":2,"AffectedSegments":[{"Line":"PEL"'
      expectedStatusCodes:
          - 200
          - 500 # Rate limited
    - name: Punggol LRT West Loop (PWL)
      url: $API_ENDPOINT
      icon: https://raw.githubusercontent.com/ngshiheng/train-service-alerts/main/assets/pwl.svg
      headers:
          - "AccountKey: $API_KEY"
          - "Content-Type: application/json"
      __dangerous__body_down: '"Status":2,"AffectedSegments":[{"Line":"PWL"'
      expectedStatusCodes:
          - 200
          - 500 # Rate limited
    - name: Sengkang LRT East Loop (SEL)
      url: $API_ENDPOINT
      icon: https://raw.githubusercontent.com/ngshiheng/train-service-alerts/main/assets/sel.svg
      headers:
          - "AccountKey: $API_KEY"
          - "Content-Type: application/json"
      __dangerous__body_down: '"Status":2,"AffectedSegments":[{"Line":"SEL"'
      expectedStatusCodes:
          - 200
          - 500 # Rate limited
    - name: Sengkang LRT West Loop (SWL)
      url: $API_ENDPOINT
      icon: https://raw.githubusercontent.com/ngshiheng/train-service-alerts/main/assets/swl.svg
      headers:
          - "AccountKey: $API_KEY"
          - "Content-Type: application/json"
      __dangerous__body_down: '"Status":2,"AffectedSegments":[{"Line":"SWL"'
      expectedStatusCodes:
          - 200
          - 500 # Rate limited

status-website:
    workflowSchedule:
        uptime: "*/5 * * * *"
    cname: sgtrains.jerrynsh.com
    logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
    name: "Train Service Status"
    introTitle: "Train Service Status"
    introMessage: "This page monitors the real-time status of all MRT and LRT lines in Singapore. Check here for service disruptions and updates."
    navbar:
        - title: Status
          href: /
        - title: GitHub
          href: https://github.com/$OWNER/$REPO
