owner: ngshiheng
repo: train-service-alerts

sites:
    - name: Train Service Alerts
      url: $API_ENDPOINT
      headers:
          - "$API_KEY"
          - "Content-Type: application/json"
      __dangerous__body_down_if_text_missing: '"Status": 1'
      expectedStatusCodes:
          - 200

status-website:
    # Add your custom domain name, or remove the `cname` line if you don't have a domain
    # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
    cname: smrt.jerrynsh.com
    logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
    name: Train Service Alerts Monitor
    introTitle: "Train Service Alerts uptime monitor and status page"
    introMessage: This status page monitors the availability of Singapore's train service alerts API. Real-time data is fetched from our [GitHub repository](https://github.com/ngshiheng/train-service-alerts). Powered by GitHub Actions, Issues, and Pages.
    navbar:
        - title: Status
          href: /
        - title: GitHub
          href: https://github.com/$OWNER/$REPO
